version: "3.9"
services:
  app:
    build: ./images/python
    ports:
      - "5000:5000"
    volumes:
      - ./app:/usr/src/app
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./conf/prometheus:/etc/prometheus/
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: always
  grafana:
    image: grafana/grafana
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./conf/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./conf/grafana/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - 3000:3000